registerJob:
  enabled: true
  image:
    registry: ghcr.io/flamingo-stack/registry
    tag: "8.9.1"


prometheus-redis-exporter:
  redisAddress: redis://redis-headless:6379
  image:
    repository: ghcr.io/flamingo-stack/registry/oliver006/redis_exporter
    tag: "v1.80.1"
