{{- $saas := index .Values "openframe-saas" -}}
{{- $svc := index $saas "stream" -}}
{{- if and $saas.enabled $svc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: openframe-stream
  labels:
    app: openframe-stream
spec:
  selector:
    app: openframe-stream
  ports:
    - port: 8082
      targetPort: http
      name: http
    - port: 8083
      targetPort: management
      name: management
  type: ClusterIP
{{- end }}
