spring:
  application:
    name: openframe-management
  config:
    import: "optional:configserver:${SPRING_CONFIG_URL:http://openframe-config.microservices.svc.cluster.local:8888}"

openframe:
  management:
    agent-configurations:
      - agent-configurations/fleetmdm-agent.json
      - agent-configurations/tacticalrmm-agent.json
      - agent-configurations/meshcentral-agent.json
      - agent-configurations/openframe-chat-agent.json