spring:
  application:
    name: openframe-management
  config:
    url: http://openframe-config.microservices.svc.cluster.local:8888
    activate:
      on-profile: k8s
    import: "optional:configserver:http://openframe-config.microservices.svc.cluster.local:8888"
nats:
  spring:
    server: nats://nats.datasources.svc.cluster.local:4222
    username: service
    password: service_pass
    connection-timeout: 30s
    max-reconnect: 10
    reconnect-wait: 5s
    ping-interval: 30s
    no-echo: true