apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: meshcentral
build:
  artifacts:
    - image: meshcentral-local
      context: .
      sync: 
        manual:
          - src: "**/*"
            dest: "/app"
      docker:
        dockerfile: Dockerfile
  local:
    useDockerCLI: false
    useBuildkit: true
    push: false
manifests:
  helm:
    releases:
      - name: meshcentral
        chartPath: ../../../manifests/integrated-tools/meshcentral
        valuesFiles:
          - ../../../manifests/integrated-tools/meshcentral/values.yaml
        # setValues:
