{
 "title": "Grafana",
 "tags": [
  "grafana",
  "monitoring",
  "platform"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"platform\", container=\"grafana\"}[2m])) by (pod) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "History",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 7, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"platform\", container=\"grafana\"}[2m])) by (pod) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"platform\", container=~\"grafana.*\"}[5m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"platform\", container=~\"grafana.*\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{namespace=\"platform\", persistentvolumeclaim=\"grafana\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    },
    {
     "expr": "kubelet_volume_stats_capacity_bytes{namespace=\"platform\", persistentvolumeclaim=\"grafana\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Grafana Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{pod=~\"grafana.*\", namespace=\"platform\"} | logfmt | line_format \"{{.msg}}\""
    }
   ]
  }
 ]
}