version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: openframe-cli
    main: ./cli/main.go
    binary: openframe
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w
      - -X github.com/flamingo-stack/openframe-oss-tenant/cmd.version={{.Version}}
      - -X github.com/flamingo-stack/openframe-oss-tenant/cmd.commit={{.Commit}}
      - -X github.com/flamingo-stack/openframe-oss-tenant/cmd.date={{.Date}}

archives:
  - builds:
    - openframe-cli
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
    wrap_in_directory: false


checksum:
  name_template: 'checksums.txt'

changelog:
  use: github-native
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - '^build:'
      - '^style:'
      - '^refactor:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
release:
  github:
    owner: flamingo-stack
    name: openframe-oss-tenant
  draft: false
  prerelease: auto
