package com.openframe.stream.enumeration;

public enum MessageType {

    MESH_MONGO_EVENT_TO_CASSANDRA,
    MESH_MONGO_EVENT_TO_KAFKA,
    TRMM_PSQL_AUDIT_LOG_TO_CASSANDRA,
    TRMM_PSQL_AUDIT_LOG_TO_KAFKA,

    OPENFRAME_MONGO_MACHINES,
    OPENFRAME_MONGO_MACHINE_TAG,
    OPENFRAME_MONGO_TAGS,

}
