registerJob:
  enabled: true
  image:
    registry: ghcr.io/flamingo-stack/registry
    tag: "8.9.1"


alloy:
  alloy:
    clustering:
      enabled: false
    stabilityLevel: "generally-available"

    configMap:
      create: false
      name: alloy-config
      key: config.alloy


  controller:
    type: daemonset
    tolerations:
      - operator: Exists
        effect: NoSchedule

  serviceAccount:
    create: true
  rbac:
    create: true

  mounts:
    varlog: true
    dockercontainers: true

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi

  livenessProbe:
    httpGet:
      path: /-/healthy
      port: 12345
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /-/ready
      port: 12345
    initialDelaySeconds: 10
    periodSeconds: 5
