deployment:
  saas:
    enabled: true
    ingress:
      localhost:
        enabled: true   # Enable localhost ingress with nginx for SaaS
      gcp:
        enabled: false
        gkeSecurityGroup: "gke-security-groups@flamingo.cx"

registry: {}

registerJob:
  enabled: true
