registerJob:
  enabled: true
servicemonitor:
  enabled: true



pinot:
  image:
    repository: apachepinot/pinot
    tag: 1.5.0
  cluster:
    name: pinot 
  server:
    replicaCount: 2
  
  controller:
    external:
      enabled: false
  broker:
    external:
      enabled: false