environment: dev

registerJob:
  enabled: true
  image:
    registry: ghcr.io/flamingo-stack/registry
    tag: "8.9.1"
servicemonitor:
  enabled: true



pinot:
  image:
    repository: apachepinot/pinot
    tag: latest
  cluster:
    name: pinot 
  server:
    replicaCount: 2
  
  controller:
    external:
      enabled: false
  broker:
    external:
      enabled: false

  zookeeper:
    image:
      repository: bitnami/zookeeper
      tag: "latest"