server:
  port: 8097

spring:
  main:
    web-application-type: servlet
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration
      - org.springframework.boot.autoconfigure.data.cassandra.CassandraDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.cassandra.CassandraReactiveDataAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.cassandra.CassandraHealthContributorAutoConfiguration
  data:
    mongodb:
      enabled: true
    cassandra:
      enabled: false
  redis:
    enabled: true
    timeout: 2000
    connect-timeout: 2000
    lettuce:
      shutdown-timeout: 2000ms
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000ms
    client-type: lettuce
  oss-tenant:
    kafka:
      bootstrap-servers: kafka.datasources.svc.cluster.local:9092
      enabled: true
  cloud:
    config:
      fail-fast: false
    function:
      definition: machineConnectedConsumer;machineDisconnectionConsumer;toolConnectionConsumer
    stream:
      enabled: true
      bindings:
        machineConnectedConsumer-in-0:
          destination: $SYS.ACCOUNT.DEVICES.CONNECT
          group: client-service-machine-connected
          content-type: application/json
        machineDisconnectionConsumer-in-0:
          destination: $SYS.ACCOUNT.DEVICES.DISCONNECT
          group: client-service-machine-disconnected
          content-type: application/json
        toolConnectionConsumer-in-0:
          destination: machine.*.tool-connection
          group: client-service-machine-tool-connection
          content-type: application/json
      binders:
        nats:
          type: nats
      default-binder: nats

management:
  server:
    port: 8102

nats:
  spring:
    server: nats://nats.datasources.svc.cluster.local:4222
    username: service
    password: service_pass
    connection-timeout: 30s
    max-reconnect: -1
    reconnect-wait: 5s
    ping-interval: 30s
    no-echo: true

jwt:
  issuer: https://auth.openframe.com
  audience: openframe-client
  publicKey:
    value: ${JWT_PUBLIC_KEY}
  privateKey:
    value: ${JWT_PRIVATE_KEY}

oauth:
  client:
    default:
      grant-types:
        - client_credentials
      scopes:
        - agent

openframe:
  oss-tenant:
    kafka:
      topics:
        outbound:
          devices-topic: devices-topic
          logs-events: logs.events
  integration:
    tool:
      enabled: true
