{{- if .Values.servicemonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pinot
  labels:
    app: pinot
spec:
  endpoints:
    - port: jmx
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
    - datasources
  selector:
    matchLabels:
      app: pinot
{{- end }}
