environment: dev

global:
  registerJob:
    enabled: true
    image:
      registry: ghcr.io/flamingo-stack/registry
      tag: "8.9.1"

postgres:
  image:
    registry: ghcr.io/flamingo-stack/registry
    repository: library/postgres
    tag: "14-alpine"

redis:
  image:
    registry: ghcr.io/flamingo-stack/registry
    repository: library/redis
    tag: "6.0-alpine"

busybox:
  image:
    registry: ghcr.io/flamingo-stack/registry
    repository: library/busybox
    tag: "1.36.1"

authentik:
  image:
    registry: ghcr.io/flamingo-stack/registry
    repository: goauthentik/server
    tag: "2024.8.3"
