flowchart TD
    Client["Client / Frontend"] --> Gateway
    Gateway --> Api

    Api --> Controller
    Controller --> Service
    Service --> Repository
    Repository --> Mongo

    Service --> Processor
