flowchart TD
    CreateRequest["CreateOrganizationRequest"] --> OrganizationMapper
    OrganizationMapper --> OrganizationEntity["Organization Entity"]

    UpdateRequest["UpdateOrganizationRequest"] --> OrganizationMapper

    OrganizationEntity --> OrganizationMapper
    OrganizationMapper --> OrganizationResponse
