flowchart TD
    Admin --> OrganizationController
    OrganizationController --> OrganizationCommandService
    OrganizationCommandService --> OrganizationRepository
    OrganizationController --> OrganizationMapper
