flowchart TD
    Admin --> SSOConfigController
    SSOConfigController --> SSOConfigService
    SSOConfigService --> SSOPerTenantConfig["Mongo Document"]
    SSOConfigService --> StrategyLayer["Provider Strategies"]
