flowchart TD
    User["User"] --> AuthUser["AuthUser"]
    User --> OAuthToken["OAuthToken"]
    Organization["Organization"]
    Device["Device"]
    CoreEvent["CoreEvent"]
    MongoRegisteredClient["MongoRegisteredClient"]
    SSOTenant["SSOPerTenantConfig"]
