flowchart TD
    Users[("users")]
    AuthUsers[("auth_users")]
    Organizations[("organizations")]
    Devices[("devices")]
    Tags[("tags")]
    MachineTags[("machine_tags")]
    Events[("events")]
    ExternalEvents[("external_application_events")]
    OAuthClients[("oauth_registered_clients")]
    OAuthTokens[("oauth_tokens")]
