flowchart TD
    RedisConnectionFactory --> CacheConfig
    KeyBuilder --> CacheConfig
    CacheConfig --> RedisCacheConfiguration
    RedisCacheConfiguration --> RedisCacheManager
    RedisCacheManager --> CacheManager
