flowchart TD
    Client --> OrganizationController
    OrganizationController --> OrganizationQueryService
    OrganizationController --> OrganizationCommandService
    OrganizationQueryService --> MongoOrg["Organization Repository"]
    OrganizationCommandService --> MongoOrg
