flowchart TD
    Debezium --> KafkaInbound
    KafkaInbound --> Deserializer
    Deserializer --> EventTypeMapper
    EventTypeMapper --> Enrichment
    Enrichment --> Cassandra
    Enrichment --> KafkaOutbound
