flowchart TD
    ConfigServer["Config Server"] --> ApiApp["API Application"]
    ConfigServer --> Gateway
    ConfigServer --> AuthServer
    ConfigServer --> StreamApp
    ConfigServer --> ManagementApp
