flowchart LR
    GatewayApp["Gateway Application"] --> ApiApp["API Application"]
    GatewayApp --> ExternalApiApp["External API Application"]

    ApiApp --> DataMongo["Data Layer Mongo"]
    ApiApp --> DataKafka["Data Layer Kafka"]

    ExternalApiApp --> ApiCore["API Service Core"]

    ApiApp --> StreamApp["Stream Application"]

    AuthApp["Authorization Server Application"] --> DataMongo

    ManagementApp["Management Application"] --> DataMongo

    StreamApp --> KafkaBroker[("Kafka Cluster")]
