flowchart TD
    ConfigServer["Config Server"] --> Api["API Application"]
    ConfigServer --> Gateway["Gateway Application"]
    ConfigServer --> Auth["Authorization Server"]
    ConfigServer --> Management["Management Application"]
    ConfigServer --> Stream["Stream Application"]
