flowchart TD
    Frontend["Frontend Tenant App"] --> Gateway
    Gateway --> AuthServer
    Gateway --> ApiApp

    ApiApp --> DataLayer["Mongo / Redis"]
    ApiApp --> Kafka

    Kafka --> StreamApp
    StreamApp --> DataLayer

    ManagementApp --> DataLayer
