apiVersion: v1
kind: Secret
metadata:
  name: mongodb
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME_BASE64}
  MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD_BASE64}
  MONGO_APP_PASSWORD: ${MONGO_APP_PASSWORD_BASE64}

