apiVersion: v2
name: grafana-wrapper
description: Wrapper chart for Grafana
type: application
version: 0.1.1
appVersion: "1.0"

dependencies:
  - name: grafana
    version: "10.2.0"
    repository: oci://ghcr.io/flamingo-stack/registry/grafana/helm-charts
