apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-secret-generator-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kafka-secret-generator-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kafka-secret-generator-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kafka-secret-generator-role
subjects:
  - kind: ServiceAccount
    name: kafka-secret-generator-sa
