#!/usr/bin/env node

/**
 * Fetches the GraphQL schema from a running DGS backend via introspection
 * and saves it as SDL (schema.graphql) for the Relay compiler.
 *
 * Usage:
 *   npm run fetch-schema                                              # uses NEXT_PUBLIC_TENANT_HOST_URL from .env
 *   npm run fetch-schema -- --token <JWT>                             # with auth token
 *   GRAPHQL_TOKEN=<JWT> npm run fetch-schema                          # token via env
 *   npm run fetch-schema -- --endpoint http://localhost:4000/api/graphql
 *   npm run fetch-schema -- --endpoint http://localhost:4000/api/graphql --token <JWT>
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

// --- Parse CLI args ---
const args = process.argv.slice(2);
function getArg(name) {
  const idx = args.indexOf(`--${name}`);
  return idx !== -1 && args[idx + 1] ? args[idx + 1] : undefined;
}

// --- Load .env file for NEXT_PUBLIC_TENANT_HOST_URL ---
function loadDotEnv() {
  const envFiles = ['.env.local', '.env'];
  for (const file of envFiles) {
    try {
      const content = readFileSync(resolve(import.meta.dirname, '..', file), 'utf-8');
      for (const line of content.split('\n')) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) continue;
        const eqIdx = trimmed.indexOf('=');
        if (eqIdx === -1) continue;
        const key = trimmed.slice(0, eqIdx).trim();
        const value = trimmed.slice(eqIdx + 1).trim();
        if (!process.env[key]) {
          process.env[key] = value;
        }
      }
    } catch {
      // file not found — skip
    }
  }
}

loadDotEnv();

const tenantHost = process.env.NEXT_PUBLIC_TENANT_HOST_URL || 'http://localhost:8080';
const ENDPOINT = getArg('endpoint') || `${tenantHost}/api/graphql`;
const TOKEN = getArg('token') || process.env.GRAPHQL_TOKEN;
const OUTPUT = resolve(import.meta.dirname, '..', 'schema.graphql');

const INTROSPECTION_QUERY = `
  query IntrospectionQuery {
    __schema {
      queryType { name }
      mutationType { name }
      subscriptionType { name }
      types {
        ...FullType
      }
      directives {
        name
        description
        locations
        args { ...InputValue }
      }
    }
  }

  fragment FullType on __Type {
    kind
    name
    description
    fields(includeDeprecated: true) {
      name
      description
      args { ...InputValue }
      type { ...TypeRef }
      isDeprecated
      deprecationReason
    }
    inputFields { ...InputValue }
    interfaces { ...TypeRef }
    enumValues(includeDeprecated: true) {
      name
      description
      isDeprecated
      deprecationReason
    }
    possibleTypes { ...TypeRef }
  }

  fragment InputValue on __InputValue {
    name
    description
    type { ...TypeRef }
    defaultValue
  }

  fragment TypeRef on __Type {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
              }
            }
          }
        }
      }
    }
  }
`;

async function fetchSchema() {
  console.log(`[fetch-schema] Fetching schema from ${ENDPOINT} ...`);
  if (TOKEN) {
    console.log('[fetch-schema] Using Bearer token for authentication');
  }

  const headers = { 'Content-Type': 'application/json' };
  if (TOKEN) {
    headers.Authorization = `Bearer ${TOKEN}`;
  }

  const response = await fetch(ENDPOINT, {
    method: 'POST',
    headers,
    body: JSON.stringify({ query: INTROSPECTION_QUERY }),
  });

  if (!response.ok) {
    throw new Error(`Introspection request failed: ${response.status} ${response.statusText}`);
  }

  const json = await response.json();

  if (json.errors?.length) {
    throw new Error(`GraphQL errors: ${json.errors.map(e => e.message).join(', ')}`);
  }

  // Dynamic import — graphql is already a project dependency
  const { buildClientSchema, printSchema } = await import('graphql');

  const schema = buildClientSchema(json.data);
  const sdl = printSchema(schema);

  const header = [
    '# Auto-generated by scripts/fetch-schema.mjs via introspection',
    `# Source: ${ENDPOINT}`,
    `# Generated: ${new Date().toISOString()}`,
    '#',
    '# Do not edit manually. Re-run: npm run fetch-schema',
    '',
  ].join('\n');

  writeFileSync(OUTPUT, header + sdl + '\n', 'utf-8');
  console.log(`[fetch-schema] Schema written to ${OUTPUT}`);
}

fetchSchema().catch(err => {
  console.error(`[fetch-schema] Failed:`, err.message);
  process.exit(1);
});
