{
 "title": "Mongo Express",
 "tags": [
  "mongo-express",
  "client-tools"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"client-tools\", container=\"mongo-express\"}[2m])) by (pod) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "History",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 7, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"client-tools\", container=\"mongo-express\"}[2m])) by (pod) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"client-tools\", container=\"mongo-express\"}[5m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"client-tools\", container=\"mongo-express\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Mongo Express Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{pod=~\"mongo-express.*\", namespace=\"client-tools\"} | logfmt | line_format \"{{.msg}}\""
    }
   ]
  }
 ]
}