spring:
  application:
    name: openframe-gateway
  config:
    url: http://openframe-config.microservices.svc.cluster.local:8888
    activate:
      on-profile: k8s
    import: "optional:configserver:http://openframe-config.microservices.svc.cluster.local:8888"

nats-ws-url: ws://nats.datasources.svc.cluster.local:8080
