{
 "title": "Health",
 "tags": [
  "overview",
  "health"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Microservices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Config",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"microservices\", container=\"openframe-config\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Management",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"microservices\", container=\"openframe-management\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"microservices\", container=\"openframe-api\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "External API",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"microservices\", container=\"openframe-external-api\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"microservices\", container=\"openframe-client\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stream",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"microservices\", container=\"openframe-stream\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth Server",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"microservices\", container=\"openframe-authorization-server\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"microservices\", container=\"openframe-gateway\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"microservices\", container=\"openframe-frontend\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Datasources/Platform", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "MongoDB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"datasources\", container=\"mongodb\"}[2m])) by (pod) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"datasources\", container=\"kafka\"}[2m])) by (pod) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pinot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_cpu_usage_seconds_total{namespace=\"datasources\", pod=~\"pinot-server.*\", container!=\"\"}) > 0 or vector(0)",
     "legendFormat": "server"
    },
    {
     "expr": "count(container_cpu_usage_seconds_total{namespace=\"datasources\", pod=~\"pinot-controller.*\", container!=\"\"}) > 0 or vector(0)",
     "legendFormat": "controller"
    },
    {
     "expr": "count(container_cpu_usage_seconds_total{namespace=\"datasources\", pod=~\"pinot-broker.*\", container!=\"\"}) > 0 or vector(0)",
     "legendFormat": "broker"
    },
    {
     "expr": "count(container_cpu_usage_seconds_total{namespace=\"datasources\", pod=~\"pinot-minion.*\", container!=\"\"}) > 0 or vector(0)",
     "legendFormat": "minion"
    }
   ]
  },
  {
   "title": "Zookeeper",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"datasources\", container=\"zookeeper\"}[2m])) by (pod) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cassandra",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"datasources\", container=\"cassandra\"}[2m])) by (pod) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"datasources\", container=\"redis\"}[2m])) by (pod) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NATS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"datasources\", container=\"nats\"}[2m])) by (pod) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"platform\", container=\"prometheus\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"platform\", container=\"grafana\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"platform\", container=\"loki\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ArgoCD",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"platform\", pod=~\"argocd.*\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alloy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"platform\", container=\"alloy\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Integrated Tools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Tactical RMM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_cpu_usage_seconds_total{namespace=\"integrated-tools\", pod=~\"tactical-backend.*\", container=\"tactical-base\"}) > 0 or vector(0)",
     "legendFormat": "backend"
    },
    {
     "expr": "count(container_cpu_usage_seconds_total{namespace=\"integrated-tools\", pod=~\"tactical-celery-.*\", container=\"tactical-base\"}) > 0 or vector(0)",
     "legendFormat": "celery"
    },
    {
     "expr": "count(container_cpu_usage_seconds_total{namespace=\"integrated-tools\", pod=~\"tactical-celerybeat.*\", container=\"tactical-base\"}) > 0 or vector(0)",
     "legendFormat": "celerybeat"
    },
    {
     "expr": "count(container_cpu_usage_seconds_total{namespace=\"integrated-tools\", pod=~\"tactical-nats.*\", container=\"tactical-base\"}) > 0 or vector(0)",
     "legendFormat": "nats"
    },
    {
     "expr": "count(container_cpu_usage_seconds_total{namespace=\"integrated-tools\", pod=~\"tactical-nginx.*\", container=\"tactical-nginx\"}) > 0 or vector(0)",
     "legendFormat": "nginx"
    },
    {
     "expr": "count(container_cpu_usage_seconds_total{namespace=\"integrated-tools\", pod=~\"tactical-websockets.*\", container=\"tactical-base\"}) > 0 or vector(0)",
     "legendFormat": "websockets"
    },
    {
     "expr": "count(container_cpu_usage_seconds_total{namespace=\"integrated-tools\", pod=~\"tactical-frontend.*\", container=\"tactical-frontend\"}) > 0 or vector(0)",
     "legendFormat": "frontend"
    }
   ]
  },
  {
   "title": "MeshCentral",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"integrated-tools\", container=\"meshcentral\"}[2m])) by (pod) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "FleetMDM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"integrated-tools\", container=\"fleetmdm\"}[2m])) by (pod) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Tactical PG",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"integrated-tools\", container=\"postgres\", pod=~\"tactical-postgres.*\"}[2m])) by (pod) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Tactical Redis",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"integrated-tools\", container=\"redis\", pod=~\"tactical-redis.*\"}[2m])) by (pod) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Mesh MongoDB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"integrated-tools\", container=\"mongodb\", pod=~\"meshcentral-mongodb.*\"}[2m])) by (pod) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Fleet MySQL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"integrated-tools\", container=\"mysql\", pod=~\"fleetmdm-mysql.*\"}[2m])) by (pod) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Fleet Redis",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"integrated-tools\", container=\"redis\", pod=~\"fleetmdm-redis.*\"}[2m])) by (pod) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Total CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(container_cpu_usage_seconds_total{}[5m]))",
     "legendFormat": "CPU %"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(container_memory_working_set_bytes{namespace=~\"microservices|datasources\"}) / sum(machine_memory_bytes)",
     "legendFormat": "Memory %"
    }
   ]
  },
  {
   "title": "Storage Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(kubelet_volume_stats_used_bytes{namespace=~\"microservices|datasources\"}) / sum(kubelet_volume_stats_capacity_bytes{namespace=~\"microservices|datasources\"})",
     "legendFormat": "Storage %"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=~\"microservices|datasources\", phase=\"Running\"} == 1)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Pods Not Ready",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=~\"microservices|datasources\", phase!=\"Running\"} == 1) or vector(0)",
     "legendFormat": "Not Ready"
    }
   ]
  }
 ]
}