{
 "title": "Platform Health Overview",
 "tags": [
  "overview",
  "platform-health"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Microservices Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"microservices\", container=\"openframe-api\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"microservices\", container=\"openframe-gateway\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Management",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"microservices\", container=\"openframe-management\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth Server",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"microservices\", container=\"openframe-authorization-server\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"microservices\", container=\"openframe-client\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Config",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"microservices\", container=\"openframe-config\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stream",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"microservices\", container=\"openframe-stream\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "External API",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"microservices\", container=\"openframe-external-api\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"microservices\", container=\"openframe-frontend\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Data Store Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Kafka",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"datasources\", pod=~\"kafka.*\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"datasources\", pod=~\"redis.*\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"datasources\", pod=~\"mongodb.*\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cassandra",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"datasources\", pod=~\"cassandra.*\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pinot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"datasources\", pod=~\"pinot.*\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zookeeper",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"datasources\", pod=~\"zookeeper.*\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NATS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"datasources\", pod=~\"nats.*\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Integrated Tools Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Tactical RMM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"integrated-tools\", pod=~\"tactical.*\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MeshCentral",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"integrated-tools\", pod=~\"meshcentral.*\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FleetMDM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=\"integrated-tools\", pod=~\"fleet.*\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Total CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(container_cpu_usage_seconds_total{namespace=~\"microservices|datasources\"}[5m])) / sum(machine_cpu_cores)",
     "legendFormat": "CPU %"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(container_memory_working_set_bytes{namespace=~\"microservices|datasources\"}) / sum(machine_memory_bytes)",
     "legendFormat": "Memory %"
    }
   ]
  },
  {
   "title": "Storage Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(kubelet_volume_stats_used_bytes{namespace=~\"microservices|datasources\"}) / sum(kubelet_volume_stats_capacity_bytes{namespace=~\"microservices|datasources\"})",
     "legendFormat": "Storage %"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=~\"microservices|datasources\", phase=\"Running\"} == 1)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Pods Not Ready",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=~\"microservices|datasources\", phase!=\"Running\"} == 1) or vector(0)",
     "legendFormat": "Not Ready"
    }
   ]
  }
 ]
}