apiVersion: v1
kind: Service
metadata:
  name: nats
spec:
  clusterIP: None
  selector:
    app: nats
  ports:
    - port: 4222
      name: client
    - port: 8222
      name: monitoring
    - port: 8080
      name: websocket
