flowchart TD
    UserController["User Controller"] --> UserService["UserService"]
    UserService --> UserRepo["User Repository"]
    UserService --> UserMapper["User Mapper"]
    UserService --> UserProcessor["UserProcessor"]
