flowchart LR
    ExternalApiApp["External API Service"] --> ExternalCore["External API Service Core"]
    ExternalApiApp --> ApiCore["Internal API"]
    ExternalApiApp --> DataLayer["Data & Persistence"]
