apiVersion: v1
kind: ConfigMap
metadata:
  name: debezium-connect-log4j
data:
  log4j.properties: |
    appenders=console
    appender.console.type=Console
    appender.console.name=STDOUT
    appender.console.layout.type=JsonTemplateLayout
    appender.console.layout.eventTemplateUri=classpath:EcsLayout.json

    rootLogger.level=INFO
    rootLogger.appenderRefs=console
    rootLogger.appenderRef.console.ref=STDOUT

    logger.zookeeper.name=org.apache.zookeeper
    logger.zookeeper.level=WARN
    logger.kafka.name=org.apache.kafka
    logger.kafka.level=WARN
    logger.connect.name=org.apache.kafka.connect
    logger.connect.level=INFO
