registerJob:
  enabled: true
servicemonitor:
  enabled: true

registry:
  docker:
    server: https://index.docker.io/v1/
    username: ""
    password: ""
    email: ""
    
image:
  repo: ghcr.io/flamingo-stack/openframe-oss-tenant/openframe-management
  tag: 67eafcccab8256bea6c0bddf90de13ed1164723f