deployment:
  saas:
    enabled: true
    ingress:
      localhost:
        enabled: false   
      gcp:
        enabled: true
        privateDomain: "internal.flamingo.cx"
        tenantID: "cluster-1001"

registry: {}

global:
  image:
    tag: latest
