apiVersion: v1
kind: Service
metadata:
  name: openframe-config
  labels:
    app: openframe-config
spec:
  selector:
    app: openframe-config
  ports:
    - port: 8888
      targetPort: http
      name: http
    - port: 8889
      targetPort: management
      name: management
  type: ClusterIP
