#!/bin/sh
set -e

RUNTIME_CONFIG_PATH="/app/public/runtime-config.js"
mkdir -p /app/public

cat > "$RUNTIME_CONFIG_PATH" <<EOF
window.__RUNTIME_CONFIG__ = {
  NEXT_PUBLIC_API_URL: "${NEXT_PUBLIC_API_URL}",
  NEXT_PUBLIC_APP_MODE: "${NEXT_PUBLIC_APP_MODE}",
  NEXT_PUBLIC_APP_TYPE: "${NEXT_PUBLIC_APP_TYPE}",
  NEXT_PUBLIC_APP_URL: "${NEXT_PUBLIC_APP_URL}",
  NEXT_PUBLIC_DEV_URL: "${NEXT_PUBLIC_DEV_URL}",
  NEXT_PUBLIC_ENABLE_DEV_TICKET_OBSERVER: "${NEXT_PUBLIC_ENABLE_DEV_TICKET_OBSERVER}",
  NEXT_PUBLIC_AUTH_CHECK_INTERVAL: "${NEXT_PUBLIC_AUTH_CHECK_INTERVAL}"
};
EOF

exec npm run start
