registerJob:
  enabled: true
  image:
    tag: "8.9.1"

servicemonitor:
  enabled: true

image:
  repository: library/nats
  tag: "2.10.10-alpine"

credentials:
  admin_user: "admin"            
  admin_pass: "admin_password"
  device_user: "machine"
  service_user: "service"
  service_pass: "service_pass"

