
registerJob:
  enabled: true
  image:
    registry: ghcr.io/flamingo-stack/registry
    repository: sap/kubectl-container
    tag: "v1.31.6"


server:
  image:
    registry: ghcr.io/flamingo-stack
    repository: fleetmdm
    tag: f23e7268e17f01e9d53dd70f17a0dc23c5da44ace15036f5f297d6cab4cb6603
  podAnnotations:
    loki.grafana.com/scrape: "true"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8070"
    prometheus.io/path: "/metrics"
