registerJob:
  enabled: true
  image:
    registry: ghcr.io/flamingo-stack/registry
    repository: sap/kubectl-container
    tag: "v1.31.6"

server:
  image:
    # Using official FleetDM image - no custom build needed
    repository: fleetdm/fleet
    tag: v4.78.0
  podAnnotations:
    loki.grafana.com/scrape: "true"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8070"
    prometheus.io/path: "/metrics"
