
registerJob:
  enabled: true
  image:
    registry: ghcr.io/flamingo-stack/registry
    repository: sap/kubectl-container
    tag: "v1.31.6"


server:
  image:
    registry: ghcr.io/flamingo-stack
    repository: fleet
    tag: 363980ad92
  podAnnotations:
    loki.grafana.com/scrape: "true"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8070"
    prometheus.io/path: "/metrics"
