apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-jmx
data:
  jmx-kafka-prometheus.yml: |
    jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:{{ .Values.kafka.metrics.jmx.kafkaJmxPort }}/jmxrmi
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    ssl: false
    whitelistObjectNames:
      - java.lang:type=GarbageCollector,*
      - java.lang:type=Memory
      - java.lang:type=Runtime
      - java.lang:type=OperatingSystem
      - java.lang:type=Threading
      - kafka.network:type=RequestMetrics,*
      - kafka.network:type=RequestChannel,*
      - kafka.network:type=Processor,*
      - kafka.log:type=Log,*
      - kafka.server:type=BrokerTopicMetrics,*
      - kafka.server:type=ReplicaManager,*
    rules:
      # GC metrics
      - pattern: 'java.lang<type=GarbageCollector, name=(.*)><>CollectionCount'
        name: jvm_gc_collection_count
        labels:
          gc: "$1"
      - pattern: 'java.lang<type=GarbageCollector, name=(.*)><>CollectionTime'
        name: jvm_gc_collection_time_ms
        labels:
          gc: "$1"
