{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace "kafka-auth" }}
{{- if not $existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: kafka-auth
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    helm.sh/resource-policy: keep
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  client-password: {{ randAlphaNum 32 | quote }}
  broker-password: {{ randAlphaNum 32 | quote }}
  cluster-id: {{ randAlphaNum 16 | quote }}
{{- end }}
