name: Release QA to Prod

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:

# =============================================================================
# JOBS
# =============================================================================

jobs:
  promote:
    name: "Create and Merge Release PR"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create QA Release Branch changes
        id: create_pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALUES_PATH: manifests/apps
        run: |
          DATE=$(date +%Y-%m-%d-%H%M)
          git checkout -b release/prod-$DATE
          cp ${VALUES_PATH}/values-qa.yaml ${VALUES_PATH}/values-prod.yaml
          sed -i "s/environment: qa/environment: prod/g" ${VALUES_PATH}/values-prod.yaml
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ${VALUES_PATH}/values-prod.yaml
          git commit -m "Promote QA to Production"
          git push -u origin release/prod-$DATE --force

      - name: Create/Merge Prod Release PR
        env:
          GH_TOKEN: ${{ secrets.PR_WRITE_ACCESS_TOKEN }}
        run: |
          PR_URL=$(gh pr create --title "Release QA to Prod" --body "Update Prod with QA values" --base main)
          gh pr review "${PR_URL}" --approve
          gh pr merge "${PR_URL}" --squash --auto
